dependencies:
- bqplot
- ipycanvas
- ipyevents
- ipyleaflet
- ipympl
- ipywidgets
- jupyterlab
- jupyterlab-drawio
- jupyterlab-fasta>=3,<4
- jupyterlab-geojson>=3,<4
- jupyterlab_miami_nights
- plotly>=5,<6
- theme-darcula
- py4macro
- py4etrics
- wooldridge
- see
- lmdiag
- linearmodels
- linearsolve
- pandas-datareader
